project:
  type: website

website:
  title: "Laboratory of Statistics and Mathematics 2025/2026"
  page-navigation: true
  sidebar: 
    background: "#3F51B5"
    pinned: true
    align: center
    style: docked
    contents:
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
    code-copy: true
    code-overflow: wrap




