project:
  type: website

website:
  title: "Laboratory of Statistics and Mathematics 2025/2026"
  page-navigation: true
  sidebar: 
    background: "#3F51B5"
    pinned: true
    align: center
    style: docked
    contents:
      - href: index.qmd
        text: Schedule
      - href: class1.qmd
        text: Introduction
      - href: resources.qmd
        text: Resources
  page-footer: 
    background: "#3F51B5"
    left: "Website made with [Quarto](https://quarto.org/) and hosted on [GitHub](https://github.com/giuseppealfonzetti/LSM)." 
    right: 
      - icon: github
        href: https://github.com/giuseppealfonzetti/LSM
      - icon: envelope
        href: mailto:giuseppe.alfonzetti@uniud.it

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
    code-copy: true
    code-overflow: wrap
